<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="PHG-IN-PF290PYX" failures="2" tests="2" name="Test(failed)" time="0.04" errors="0" timestamp="17 Jul 2023 06:58:29 GMT">
  <testcase classname="test_case.cases" name="TestCases1" time="0.014">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at test_case.cases.TestCases1(cases.java:9)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- TestCases1 -->
  <testcase classname="test_case.cases" name="TestCases2" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at test_case.cases.TestCases2(cases.java:13)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- TestCases2 -->
  <testcase classname="test_case.cases" name="TestCases3" time="0.0">
    <ignored/>
  </testcase> <!-- TestCases3 -->
</testsuite> <!-- Test(failed) -->
